# Site settings
title: Think2019 Hands-On Lab 6051
email: dcacy@us.ibm.com
description: >
  Using Domino Query Language and Node.js — Domino Developers Edition!

baseurl: "/think2019lab-domino-nodejs" # the subpath of your site, e.g. /blog/
url: https://icstechsales.github.io/think2019lab-domino-nodejs # the base hostname & protocol for your site
git_address: https://github.com/icstechsales/think2019lab-node-jsdomino
git_edit_address: https://github.com/icstechsales/think2019lab-domino-nodejs/tree/gh-pages

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: America/Los Angeles
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
