# Site settings
title: NodeRED dominodb Documentation
email: stefano@poglianis.net
description: >
  NodeRED dominodb Documentation.

baseurl: "/think2019lab-domino-integration" # the subpath of your site, e.g. /blog/
url: https://github.com/icstechsales/think2019lab-domino-integration # the base hostname & protocol for your site
git_address: https://github.com/icstechsales/think2019lab-domino-integration
git_edit_address: https://github.com/icstechsales/think2019lab-domino-integration/tree/gh-pages

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
