# Site settings
title: ICP 3.1.2 PoT
email: dcacy@us.ibm.com
description: >
  Lab documentation for the ICP 3.1.2 PoT

baseurl: "/icp-312-pot" # the subpath of your site, e.g. /blog/
url: https://dcacy.github.io/icp-312-pot # the base hostname & protocol for your site
git_address: https://github.com/dcacy/icp-312-pot
git_edit_address: https://github.com/dcacy/icp-312-pot/tree/icp-312-pot

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
# plugins:
#   - jekyll-feed
#   - jekyll-redirect-from
#   - jekyll-seo-tag
#   - jekyll-sitemap

exclude:  
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - README.md
  - .vscode
  
timezone: America/Chicago
defaults:
# - scope:
#     path: _posts
#     type: posts
#   values:
#     layout: post
#     sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
